### ISSUE TITLE
main 函数第58行运行时错误

### ISSUE THREAD

**Issue by aeroplanepaper** [whexy/SUSTech_Xuanke#1]
'execution': re.findall('on" value="(.+?)"', r.text)[0],
NameError: name 'r' is not defined
输入账号密码后就会闪退

**Comment by whexy** [comment]
Thought you meant 'Runtime Error' not 'Compiling Error' since there's no compiling in Python. 😄
Code is written for 2019-2020-2 semester. Right now the URL is totally different. I won't fix that until the whole course-choosing process is over for my own safety. But you can fix it yourself since it's a very simple one.
Thanks again for this issue.

**Comment by whexy** [comment]
Problem solved with whexy@8de77a3d30a5730821e4a7641015a4591f31986b.
